name: Actualizar Partidos

on:
  schedule:
    - cron: '0 3 * * *' # Se ejecuta todas las noches a las 3 AM
  workflow_dispatch: # Permite ejecutarlo manual

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Ejecutar script
        run: python update_matches.py
      - name: Guardar cambios
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add stats.json
          git commit -m "Actualización automática de partidos" || exit 0
          git push
